language: node_js
node_js:
  - "7"
env:
- secure: "GmbJgj2M+Zjp3Is2XUL6yQJj5ewFQJG8ubU+QHi7MRh6zUFngS8YUcRZH7dk96bWgg7JbkETOs3j3s1I4ffw+R0qgEjfmHeop3bl/2DhUsjJhmfMVoUgRd7W0WcMPRv0eHJ6os9+vBbRtieeQjqQLZcD9WCr8AY9wlqOJi6esnhB3sIi7s8lL7szwnpsg6Bq6BkVFALcGD3dSfEv3XXXk3uhsjOZO15mTf/NBn5yWB7wvWUaYt5GXa/+Rph7SQ6VskcDtp5TWoEFXkcM2fj/78b/V5kkHL7mCd2zqH00v+BhC3Xd5lMTAyhoIkuDpNvgN/SsmwiQs7PBOx2Mj1gL14A2PFJ2204VNktJJJxA0HxzyrwfhZUdGgG4IOIxTy7DjTW4bNwF4hgtZZEN9g98V4ILs7xw6ylkEFrZtc1i3PLZCAaIn7atlV6/I31EqC+ec1zJkbrsshNyaGS0odh1KRlQO2SIe0wF3qI7p4NNzdEF+rVIr7FfFEVMzaz+a/T6an+apONvSgqZJgz6R2oFT0epFzgRwpP1AG8OWHyWOkU76jswBBbYzTyGudHk2XSPysOZz+Uw2PpeWXadlKK2sX278FUggfzpyXlisSIVy4zwWZ45ajFmVdaApf96VGsPlaYNshHNHoN6nI9L37+FKeVggq+CXLxAgVmw5sfv44E="

script:
- npm install
- npm run test
