language: node_js
node_js:
  - "7"
env:
- secure: "urDf2RiFWNO+a/tKwtiJ9oQuNxr6+wvl4U3pEzK3zenJmhluqMcNeMqYNvSL592rYYBy/BXi5y+BIx1zAWdAcX0QnFkbqRq9iZkfxFlHBgbAENxFLzMlGeUGeUgku6lMXGxZJEVDA+FhGMdtI0Ergyv5ZRykNmSYkRMDfa8U3l3vPEI5zHAqRULW07e6J2JbWGyOvdr3kEz2IMlyme1RowFJdYwGttKikOb2V7TByDRnu1w1yvgDxxEFGWJYq54cNBhBxu3ezuKzmHLpfmr8jqJE5n5VfpTk52MqKy/n9iueyuSWb9J7V8Bd6XyLn0+zO80GE9+zTZ3PBQuX839zWwLqB912LqzQmjNoGWkMI7wxWqKsWHFduIOcnaMlrnUwL729UYxxN4L/ynL0hKNhQmJ7cZW4aONI1AYJ2RuPYW1Zmzz1eWoKLl+MNcSwfmE43JcFU8Ryl4yX4hUezl760ArcIu+6TDOEEcIJp4Pwlw36odK+2KMNYQEj7rNyZIAM7DIhnmZ6OkL1efIcdzAC0U6HWuWngL6T05DTQiOMVoTOfCQHJO4Yyl/FSK6xG9KivLs3zkf4E1mPLub0/8qLgoPWWo3MQ8gXACZ1oHx2OYDLmiMr7j/yLKgP3404d4WLDgaIbIknQ3xUCeCrE9MVswUUJK2dKHuIvI74IG5DMq4="

script:
- npm install
- npm run lint
- npm run test
